build = "cargo build --all-features"
build-rel = "cargo build --all-features --release"
markup = "cargo build --no-default-features --features markup --release -p 'pdfitdown'"
office = "cargo build --no-default-features --features office --release -p 'pdfitdown'"
image = "cargo build --no-default-features --features image --release -p 'pdfitdown'"
markup-cli = "cargo build --no-default-features --features markup,cli --release -p 'pdfitdown'"
image-cli = "cargo build --no-default-features --features image,cli --release -p 'pdfitdown'"
office-cli = "cargo build --no-default-features --features office,cli --release -p 'pdfitdown'"
build-wasm = "cargo build --target wasm32-unknown-unknown"
build-wasm-rel = "cargo build --target wasm32-unknown-unknown --release"
build-wasip = "cargo build --target wasm32-wasip1"
build-wasip-rel = "cargo build --target wasm32-wasip1 --release"
clippy = "cargo clippy --all-targets --all-features"
clippy-fix = "cargo clippy --all-targets --all-features --fix --allow-dirty"
format = "cargo fmt --all -- --check"
format-fix = "cargo fmt --all"
test = "cargo test --release -p 'pdfitdown'"
test-rayon = "cargo test --features rayon --release -p 'pdfitdown'"
test-markup = "cargo test --no-default-features --features markup --release -p 'pdfitdown'"
test-office = "cargo test --no-default-features --features office --release -p 'pdfitdown'"
test-image = "cargo test --no-default-features --features image --release -p 'pdfitdown'"
