/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PdfItDownConverter {
  constructor()
  convertBytes(input: Buffer): Buffer
  convertFile(inputFile: string, outputFile: string, overwrite: boolean): void
  convertMultipleFiles(inputFiles: Array<string>, outputFiles: Array<string>, overwrite: boolean): void
  convertDirectory(directory: string, overwrite: boolean, recursive: boolean): void
}
